// Page file to SEO key mapping
// This maps each page file path to its corresponding SEO key in seo.ts

export const pageToSeoKeyMapping: Record<string, string> = {
    // Main Pages
    'HomePage.tsx': 'home',
    'HomePageOptimized.tsx': 'home',
    'About.tsx': 'about',
    'ContactPage.tsx': 'contact',
    'PricingPage.tsx': 'pricing',
    'PricingAndPlanPage.tsx': 'pricing-and-plan',
    'FeaturesPage.tsx': 'features',
    'ProductPage.tsx': 'products',

    // Services & Solutions
    'EnterprisePage.tsx': 'solutions-enterprise',
    'EducationPage.tsx': 'solutions-education',
    'GovernmentPage.tsx': 'solutions-government',
    'HealthcareServices.tsx': 'solutions-healthcare',
    'FinancialServices.tsx': 'solutions-financial-services',
    'ITADPage.tsx': 'solutions-itad',
    'ServiceProvidersPage.tsx': 'solutions-service-providers',

    // Products
    'DriveEraserPage.tsx': 'products-drive-eraser',
    'FileEraserPage.tsx': 'products-file-eraser',
    'MobileErasureSolutions.tsx': 'products-mobile-erasure',
    'CloudErasurePage.tsx': 'services-cloud-erasure',

    // Support & Documentation
    'SupportPage.tsx': 'support',
    'DownloadPage.tsx': 'downloads',
    'FAQPage.tsx': 'faq',
    'FreeTrialPage.tsx': 'free-trial',
    'RequestDemoPage.tsx': 'request-demo',
    'LiveDemoPage.tsx': 'live-demo',
    'SearchDemoPage.tsx': 'search-demo',

    // Partners
    'PartnersPage.tsx': 'partners',
    'PartnerProgramPage.tsx': 'partner-program',
    'ResellersPage.tsx': 'resellers',
    'AffiliatesPage.tsx': 'affiliates',

    // Resources
    'ResourcesPage.tsx': 'resources',
    'BlogPage.tsx': 'blog',
    'NewsPage.tsx': 'news',
    'PressPage.tsx': 'press',
    'EventsPage.tsx': 'events',
    'WebinarsPage.tsx': 'webinars',
    'TrainingPage.tsx': 'training',
    'CaseStudiesPage.tsx': 'resources-case-studies',
    'WhitepapersPage.tsx': 'resources-whitepapers',
    'DocumentationPage.tsx': 'resources-documentation',
    'CustomerStoriesPage.tsx': 'customer-stories',
    'TestimonialsPage.tsx': 'testimonials',
    'ReviewsPage.tsx': 'reviews',
    'UseCasesPage.tsx': 'use-cases',

    // Compliance & Legal
    'CompliancePage.tsx': 'compliance',
    'PrivacyPolicy.tsx': 'privacy-policy',
    'TermsConditionsPage.tsx': 'terms-conditions',
    'TermsOfServicePage.tsx': 'terms-of-service',
    'CookiePolicyPage.tsx': 'cookie-policy',
    'LegalPolicy.tsx': 'legal',

    // Industries
    'BankingFinancePage.tsx': 'industries-banking-finance',
    'RetailPage.tsx': 'industries-retail',
    'ManufacturingPage.tsx': 'industries-manufacturing',
    'TelecommunicationsPage.tsx': 'industries-telecommunications',

    // Company
    'CareersPage.tsx': 'careers',
    'TeamPage.tsx': 'team',
    'LeadershipPage.tsx': 'leadership',
    'IntegrationsPage.tsx': 'integrations',
    'ImplementationPage.tsx': 'implementation',
    'ProfessionalServicesPage.tsx': 'professional-services',
    'ConsultingPage.tsx': 'consulting',

    // Support Guides
    'WipeGuide.tsx': 'support-wipe-guide',
    'OverwriteGuide.tsx': 'support-overwrite-guide',
    'CryptoEraseSSD.tsx': 'support-ssd-cryptographic-erasure-guide',
    'FileEraserGuide.tsx': 'support-file-eraser-guide',
    'MacEraseGuide.tsx': 'support-mac-eraser-guide',
    'WipeMacM1.tsx': 'support-mac-wipe-guide',
    'WipeSASDrive.tsx': 'support-sas-wipe-guide',
    'SecureEraseHDDSSD.tsx': 'support-secure-erase-hddssd',
    'CloudConsoleGuide.tsx': 'support-cloud-console-guide',
    'RetainOSGuide.tsx': 'support-retain-os-guide',
    'GetStartedPage.tsx': 'support-get-started',
    'KnowledgeBasePage.tsx': 'support-knowledge-base',
    'ProductVideosPage.tsx': 'support-product-videos',

    // Admin Pages
    'admin/AdminGroups.tsx': 'groups',
    'admin/AddGroup.tsx': 'groups-add',
    'admin/AddUser.tsx': 'users-add',
    'admin/AdminUsers.tsx': 'users',
    'admin/AdminReports.tsx': 'reports-admin',
    'admin/LicensesPage.tsx': 'licenses',
    'admin/MachinesPage.tsx': 'machines',
    'admin/SessionsPage.tsx': 'sessions',
    'admin/SettingsPage.tsx': 'settings',
    'admin/SubusersPage.tsx': 'subusers',
    'admin/ProfileEditPage.tsx': 'profile-edit',
    'admin/EditSubuserPage.tsx': 'edit-subuser',
    'admin/ReportsPage.tsx': 'reports',
    'admin/GenerateReportPage.tsx': 'reports-generate',

    // Auth Pages
    'auth/LoginPage.tsx': 'login',
    'auth/RegisterPage.tsx': 'register',

    // Manual Pages - Help Manual
    'manual/HelpManualIndexPage.tsx': 'support-help-manual',
    'manual/CompleteManualPage.tsx': 'support-help-manual-complete-manual',
    'manual/CompleteNetworkManualPage.tsx': 'support-help-manual-complete-network-manual',
    'manual/DSecureFAQPage.tsx': 'support-help-manual-faqs',
    'manual/ReportManagementPage.tsx': 'support-help-manual-report-management',
    'manual/ScheduleSettingsPage.tsx': 'support-help-manual-schedule-settings',
    'manual/WorkingGuidePage.tsx': 'support-help-manual-working-guide',

    // Manual Pages - Network File
    'manual/network-file/About.tsx': 'support-manual-navigation',
    'manual/network-file/ErasingFiles.tsx': 'erasing-files',
    'manual/network-file/ErasingTraces.tsx': 'erasing-traces',
    'manual/network-file/FAQ.tsx': 'support-manual-faqs',
    'manual/network-file/Installation.tsx': 'installation',
    'manual/network-file/Licensing.tsx': 'licensing',
    'manual/network-file/Performance.tsx': 'performance',
    'manual/network-file/QuickOverview.tsx': 'quick-overview',
    'manual/network-file/ReportManagement.tsx': 'report-management',
    'manual/network-file/SchedulingTasks.tsx': 'scheduling-tasks',
    'manual/network-file/UserInterface.tsx': 'user-interface',

    // Support Manual Pages
    'support/manual/AccessVerification.tsx': 'support-manual-access-verification',
    'support/manual/ActivationKey.tsx': 'support-manual-activation-key',
    'support/manual/ApiIntegration.tsx': 'support-manual-api-integration',
    'support/manual/AuditPreparation.tsx': 'support-manual-audit-preparation',
    'support/manual/AuditTrails.tsx': 'support-manual-audit-trails',
    'support/manual/AutoUpdates.tsx': 'support-manual-auto-updates',
    'support/manual/BankingFinance.tsx': 'support-manual-banking-finance',
    'support/manual/BankingMode.tsx': 'support-manual-banking-mode',
    'support/manual/BatchOperations.tsx': 'support-manual-batch-operations',
    'support/manual/BestPractices.tsx': 'support-manual-best-practices',
    'support/manual/Certificates.tsx': 'support-manual-certificates',
    'support/manual/CloudConsole.tsx': 'support-manual-cloud-console',
    'support/manual/CommonIssues.tsx': 'support-manual-common-issues',
    'support/manual/Compliance.tsx': 'support-manual-compliance',
    'support/manual/CryptoErasure.tsx': 'support-manual-cryptographic-erasure',
    'support/manual/CustomAlgorithms.tsx': 'support-manual-custom-algorithms',
    'support/manual/CustomConfigs.tsx': 'support-manual-custom-configs',
    'support/manual/CustomDashboards.tsx': 'support-manual-custom-dashboards',
    'support/manual/Degaussing.tsx': 'support-manual-degaussing-method',
    'support/manual/DeviceSelection.tsx': 'support-manual-device-selection',
    'support/manual/DownloadInstaller.tsx': 'support-manual-download-installer',
    'support/manual/EnterpriseIntegration.tsx': 'support-manual-enterprise-integration',
    'support/manual/ErasureProcess.tsx': 'support-manual-erasure-process',
    'support/manual/ErasureReports.tsx': 'support-manual-erasure-reports',
    'support/manual/ErrorCodes.tsx': 'support-manual-error-codes',
    'support/manual/FAQs.tsx': 'support-manual-faqs',
    'support/manual/FirstRun.tsx': 'support-manual-first-run',
    'support/manual/FirstScan.tsx': 'support-manual-first-scan',
    'support/manual/FirstTimeSetup.tsx': 'support-manual-first-time-setup',
    'support/manual/GeneralSettings.tsx': 'support-manual-general-settings',
    'support/manual/Installation.tsx': 'support-manual-installation',
    'support/manual/InstallationGuide.tsx': 'support-manual-installation-guide',
    'support/manual/KeyActivation.tsx': 'support-manual-key-activation',
    'support/manual/KeyboardShortcuts.tsx': 'support-manual-keyboard-shortcuts',
    'support/manual/LicenseActivation.tsx': 'support-manual-license-activation',
    'support/manual/Limitations.tsx': 'support-manual-limitations',
    'support/manual/Linux.tsx': 'support-manual-linux',
    'support/manual/MacOS.tsx': 'support-manual-macos',
    'support/manual/MainDashboard.tsx': 'support-manual-main-dashboard',
    'support/manual/Mobile.tsx': 'support-manual-mobile',
    'support/manual/Navigation.tsx': 'support-manual-navigation',
    'support/manual/Nist80088.tsx': 'support-manual-nist-800-88',
    'support/manual/Performance.tsx': 'support-manual-performance',
    'support/manual/PhysicalDestruction.tsx': 'support-manual-physical-destruction',
    'support/manual/PreInstallation.tsx': 'support-manual-pre-installation',
    'support/manual/ProgressMonitoring.tsx': 'support-manual-progress-monitoring',
    'support/manual/Quickstart.tsx': 'support-manual-quickstart',
    'support/manual/Recovery.tsx': 'support-manual-recovery',
    'support/manual/RemoteManagement.tsx': 'support-manual-remote-management',
    'support/manual/Scripting.tsx': 'support-manual-scripting',
    'support/manual/Servers.tsx': 'support-manual-servers',
    'support/manual/SetupWizard.tsx': 'support-manual-setup-wizard',
    'support/manual/Shredding.tsx': 'support-manual-shredding-method',
    'support/manual/SystemRequirements.tsx': 'support-manual-system-requirements',
    'support/manual/SystemScanning.tsx': 'support-manual-system-scanning',
    'support/manual/UseCases.tsx': 'support-manual-use-cases',
    'support/manual/UserInterface.tsx': 'support-manual-user-interface',
    'support/manual/UserManagement.tsx': 'support-manual-user-management',
    'support/manual/UserProfile.tsx': 'support-manual-user-profile',
    'support/manual/VerificationMethods.tsx': 'support-manual-verification-methods',
    'support/manual/Windows.tsx': 'support-manual-windows',

    // Blog Pages
    'blog/DataDeletionMyths.tsx': 'blog-data-deletion-myths',
    'blog/DataSanitizationCompliance.tsx': 'blog-data-sanitization-compliance',
    'blog/ErasureVsDestruction.tsx': 'blog-erasure-vs-destruction',
    'blog/OverwriteGuide.tsx': 'blog-overwrite-guide',
    'blog/SSDWipeGuide.tsx': 'blog-ssd-wipe-guide',

    // Other Pages
    'ROICalculatorPage.tsx': 'roi-calculator',
    'ApiTestPage.tsx': 'api-test',
    'DiagnosticsPage.tsx': 'diagnostics',
    'ForumPage.tsx': 'forum',
    'IconShowcase.tsx': 'icon-showcase',
    'NotFoundPage.tsx': '404',
    'OrderSuccessPage.tsx': 'order-success',
    'PaymentPage.tsx': 'payment',
    'PaymentSetupPage.tsx': 'payment-setup',
    'CheckoutPage.tsx': 'checkout',
    'ReleaseNotesPage.tsx': 'release-notes',
    'CloudIntegrationPage.tsx': 'cloud-integration',
    'ConnectingDomainPage.tsx': 'connecting-domain',
    'PrivateCloudSetupPage.tsx': 'private-cloud-setup',
};

export default pageToSeoKeyMapping;
